### ISSUE TITLE
Why use a let here?

### ISSUE THREAD

**Issue by joostf** [aaraar/progressive-web-apps-1920#5]
https://github.com/aaraar/progressive-web-apps-1920/blob/2dbe22f1f5b12a987f1f82636b13704e33099cbe/data/tasks/compress.js#L15

**Comment by aaraar** [comment]
I push extra directories to the array when looping over a JSON file. Maybe recursivly reading the directories would be best practice, but this was much easier to wrap my head around https://github.com/aaraar/progressive-web-apps-1920/blob/2dbe22f1f5b12a987f1f82636b13704e33099cbe/data/tasks/compress.js#L19
